#!/bin/bash

set -e

NAME="$(basename $0)"

[[ "$#" -ge 1 && "$#" -le 3 ]] \
    || { echo "Usage: ${NAME} filePath [alertAfterSeconds] [email]" >&2; exit 1; }

filePath=${1}
alertAfterSeconds=${2-360}
email=${3}

currentTime=$(date +%s)
changedTime=$(stat --format %Y ${filePath})
deltaSeconds=$((currentTime-changedTime))

if [[ ${deltaSeconds} -ge ${alertAfterSeconds} ]]; then
    host=$(hostname --fqdn)
    message="${NAME}\n\nHost: ${host}\nDate: $(date)\nAlert after seconds: ${alertAfterSeconds}"
    message+="\n---\nFile: ${filePath}\nLast changed: ${deltaSeconds} seconds ago"
    echo -e "${message}"
    if [[ -n "${email}" ]]; then
        echo -e "${message}" | mail -s "${NAME} triggered on ${host}" "${email}"
    fi
fi
